package com.nagarro.booking.enums;

public enum BookingStatus {
	PROCESSING,	
	VERIFYING_PAYMENT,
	PAYMENT_FAILED,
	ACCEPTED,
	NOT_ACCEPTED_BY_WORKER,
	WORKER_ASSIGNED,
	CANCELLED_BY_CUSTOMER,
	COMPLETED
}